http:
  routers:
    chomsky:
      entryPoints:
        - "secureport"
      rule: "PathPrefix(`/api/v1`)"
      service: chomsky-serve
      tls: true
      middlewares:
        - "api-stripprefix"

  middlewares:
    api-stripprefix:
      stripPrefix:
        prefixes:
          - "/api/v1"
        forceSlash: false

  services:
    # Define how to reach an existing service on our infrastructure
    chomsky-serve:
      loadBalancer:
        servers:
          - url: http://chomsky-container:8000/

tls:
  certificates:
    - certFile: "/etc/certs/star_ameyo_net.crt"
      keyFile: "/etc/certs/star_ameyo_net.key"
      stores:
        - default
