global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false

  file:
    filename: /etc/traefik/config.yml
    watch: true

log:
  level: INFO
  format: common

entryPoints:
  insecureport:
    address: ":80"
    http:
      redirections: 
        entryPoint:
          to: secureport
          scheme: https
  secureport:
    address: ":443"
